image: ruby:2.5
stages:
- build
- deploy

before_script:
  - apt-get update >/dev/null
  - apt-get install -y locales >/dev/null
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8

build site:
  stage: build
  script:
    - ./scripts/ci.sh
  variables:
    JEKYLL_ENV: production
  artifacts:
    expire_in: 1 month
    paths:
      - _site
  cache:
    paths:
      - vendor

.deploy site:
  stage: deploy
  script:
    - ./scripts/deploy.sh
  only:
    - master